### ISSUE TITLE
Add supported mutator descriptions

### ISSUE THREAD

**Issue by nicojs** [stryker-mutator/stryker-mutator.github.io#1]
Also link stryker-readme back to this page

**Comment by simondel** [comment]
I have started working on this page on the [mutators branch](https://github.com/stryker-mutator/stryker-mutator.github.io/tree/mutators).

I still have to do some formatting but right now the mutators are described in markdown and the page looks like this:

![image](https://cloud.githubusercontent.com/assets/4221997/17249266/7e92dfc8-559f-11e6-9d74-a615c8bd4a87.png)
