### ISSUE TITLE
Fix description meta tag

### ISSUE THREAD

**Issue by nicojs** [stryker-mutator/stryker-mutator.github.io#103]
The description meta tag is broken since our redesign:
![description-meta-tag-broken.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5ac1edcf332454001298d1a1/125516c66e82c728ace21e0d46ec918920908ab99be0b04de950f580280b33722e49a1397f8ee626fd0e39111d0014f9121c4d4eeefcd878a7e36f248d0e5aebd9645774c63e40f8bf841eb702a83c990dd4e8e8d51199a26867f5819d4e3914041d8dff5831a0904ccc5af34ff300.png)

**Comment by nicojs** [comment]
Very much still broken! Do your magic 👍

**Comment by kmdrGroch** [comment]
@nicojs small question. In blogs, it should be `Stryker: Blog` or `Stryker: name of the specific blog`?

**Comment by kmdrGroch** [comment]
![image](https://user-images.githubusercontent.com/28489774/49341952-8d1d6600-f654-11e8-8a94-df7ac0f34196.png)

**Comment by kmdrGroch** [comment]
(@nicojs still waiting for checking PR ;p 🤓 )

**Comment by kmdrGroch** [comment]
@nicojs to be closed

**Comment by nicojs** [comment]
Thanks!

Pro tip, adding "Fixes #103" to your PR will make sure it is closed automatically when the PR is merged :+1:

**Comment by kmdrGroch** [comment]
i had this line :/ i dunno. I think it didn't work since i have written `fixes: #103`... strange

**Comment by nicojs** [comment]
Yeah, it is kind of strict...
