### ISSUE TITLE
Enrich blogs with authors and labels

### ISSUE THREAD

**Issue by nicojs** [stryker-mutator/stryker-mutator.github.io#118]
We should enrich our "blogs" section with authors and labels. For example, we could create tabs for "all", "Stryker", "Stryker.NET" and "Stryker4s". We could also add an "About the author" part with a small text about the author with a picture.

**Comment by hugo-vrijswijk** [comment]
Pictures and names are always good. Shouldn't be too difficult if we use something like Gravatar

**Comment by legopiraat** [comment]
We could use the github api for parts of the information.

https://developer.github.com/v3/users/#get-a-single-user

We could get the username, some bio, gravatar.

**Comment by hugo-vrijswijk** [comment]
Closed with #146
