### ISSUE TITLE
Enrich blogs with comments section.. ?

### ISSUE THREAD

**Issue by nicojs** [stryker-mutator/stryker-mutator.github.io#119]
Do we want to enrich our blogs with a "comments" section? I don't want to build a new comments backend from scratch, maybe we can use a serverless comment engine? More research needs to be done on this part.

Not sure if we need comments, we first need to decide on that. @stryker-mutator/contributors ?

**Comment by rouke-broersma** [comment]
Disqus adds ads to our site unless we use a paid account and I find that it generally does not look the best unless your colour scheme closely matches disqus. Perhaps something like https://staticman.net/ could work for us.

**Comment by rouke-broersma** [comment]
I have integrated https://giscus.app/ with my blog. It uses github discussions as the comment database, and you can use github discussions for moderation. It does not use any external service, it's some javascript you inject into the page, which injects a github discussions 'new post' iframe or something like that. Users authorize with github and place the discussion post as their own user. The javascript in the blog article simply requests all comments on the discussion for that blog article client side.
