### ISSUE TITLE
Make it easier to link to specific sections

### ISSUE THREAD

**Issue by ollelauribostrom** [stryker-mutator/stryker-mutator.github.io#123]
Let's say I want to link to a specific section of a page, maybe the example on the landing page or some specific section of a blog post. It would be conventient to quickly get the direct link to that section, like for instance `http://stryker-mutator.io/#an-example`.

I like how this works on GitHub where a small clickable icon appears when hovering a heading. Clicking that icon updates the url to point to that section. Looks like this:
<img width="256" alt="skarmavbild 2019-02-26 kl 17 38 31" src="https://user-images.githubusercontent.com/16004130/53429683-666d9200-39ed-11e9-8f98-457839aec7e2.png">

**Comment by nicojs** [comment]
Great idea. 

As a workaround: I've already added a pugjs plugin that adds an `id` to each header tag, so you can already link to it manually.

**Comment by hugo-vrijswijk** [comment]
The [markdown plugin we use already supports this](https://www.npmjs.com/package/markdown-it-anchor#usage), so it should just be a case of enabling the option and making sure it looks nice

**Comment by hugo-vrijswijk** [comment]
Fixed in #124
