### ISSUE TITLE
Load documentation from github sources

### ISSUE THREAD

**Issue by richardwerkman** [stryker-mutator/stryker-mutator.github.io#132]
At Stryker.NET we are strugling to find a good place to document our installation instructions,  mutators and reporters. In the current situation we have 3 places available:
- `stryker-net github`
- `stryker handbook github`
- `stryker-mutator.io`

None of the locations seem ideal. In the handbook we can keep all stryker versions in one place. But it requires seperate pull requests for every feature. One implementation and one documentation. 

On the stryker-net github seems ideal since we can request each PR to update the documentation as well. This makes keeping the implementation and documentation in sync more easy.

## Proposal
We would load the markdown found in specific files and place it on the website every night. This gives us one place where all stryker documentation comes together and still gives us the best case of 1 place with implementation and documentation together.

We could even try to give each stryker version a `/docs` folder in the repo, and create a page for each `*.md` file found.

## Benefits
Placing all documentation on the website creates a great place to discover all about stryker. In the current situation the documentation is partly scatered over different places.

**Comment by nicojs** [comment]
Sounds like a good idea. We should make it so that the website (publish) build fetches the `master` branch of the different Stryker repo's and places those under the "handbook" of the website. 

We could use the "stryker-handbook" for global Stryker stuff.

It would be nice to also show an edit button (with a pencil ✏) so people can easily edit the github sources.

@hugo-vrijswijk could you add this by any change?

**Comment by hugo-vrijswijk** [comment]
I also like this! Though thinking about it, I feel like the website is getting more and more features that other "website packages" already have (this, comments, authors, etc). So it makes me wonder if setting up a whole new pipeline to do this is worth it, versus switching to something more general

**Comment by hugo-vrijswijk** [comment]
Closed with #146
