### ISSUE TITLE
Special character not rendered correctly

### ISSUE THREAD

**Issue by korthout** [stryker-mutator/stryker-mutator.github.io#140]
My browser is not rendering some special character correctly. Likely it is an emoji for external links. It could juist be a fault of my computer, but just wanted to inform. See this screenshot from the latest blog post at https://stryker-mutator.io/blog/2019-12-27/stryker-dashboard-host-your-mutation-testing-report.

![image](https://user-images.githubusercontent.com/3511026/71661541-cdb34b80-2d4e-11ea-88c0-f060e90e4793.png)

**Comment by korthout** [comment]
Suggestion: https://fontawesome.com/v4.7.0/icon/external-link

**Comment by hugo-vrijswijk** [comment]
It's not an emoji, but already an icon from font-awesome (I think), set here: https://github.com/stryker-mutator/stryker-mutator.github.io/blob/develop/src/scss/stryker/links.scss#L2

What it's supposed to look like:
![image](https://user-images.githubusercontent.com/10114577/71662376-9003f200-2d51-11ea-8c7f-e517af9459b7.png)


I can only reproduce this on my phone (both Firefox and Chrome mobile) but not on my desktop (Windows) in any browser

**Comment by hugo-vrijswijk** [comment]
Fixed in #141
