### ISSUE TITLE
Create blog article calendar

### ISSUE THREAD

**Issue by simondel** [stryker-mutator/stryker-mutator.github.io#15]
We need a calendar for our blog posts in early 2017

**Comment by avassem85** [comment]
- [ ] Happy New Year with Stryker (@avassem85)
-- 2017 invest in code quality
-- Hack-a-thon / relation Info Support
-- Results of this week / stats
- [ ] Mutation Testing (@simondel)
-- What is Mutation Testing
-- Why do Mutation Testing
-- Other articles on Mutation Testing
- [ ] Getting Started with Stryker (@avassem85)
-- Use stryker with a known open source project
- [ ] Advanced Use Cases with Stryker (@nicojs)
-- Possibilities with Stryker to use it with different runners/frameworks
- [ ] Embed Stryker in your continuous delivery pipeline with SonarCube
- [ ] How does Stryker work - Speed (@nicojs)
- [ ] How does Stryker work - Plugin Model (@nicojs)
- [ ] Use Stryker with custom Testrunners (@nicojs)
- [ ] How does Stryker work - TypeScript (@nicojs)
-- Why use TypeScript

Other possibilities
- DotNetFlix about Stryker
- Show your code youtube channel

**Comment by nicojs** [comment]
This is all done. Time to create  a new calendar... in a new issue 😄
