### ISSUE TITLE
Integrating Stryker.NET in your azure pipelines post could be updated

### ISSUE THREAD

**Issue by raschmitt** [stryker-mutator/stryker-mutator.github.io#191]
I think [this](https://stryker-mutator.io/blog/2020-05-15/azure-pipelines-integration) was a great post about how stryker can be integrated into an Azure DevOps pipeline.

Yet as there is [this know issue](https://github.com/dotnet/sdk/issues/8999), of running dotnet tools right after instaling it on azure, that I personally have been experiencing way too often and Microsoft doesn't seem to be fixing it anytime soon, I think the post should be updated to discuss this and propose a work-around.

**Comment by rouke-broersma** [comment]
We have a docs page now with this information: https://stryker-mutator.io/docs/stryker-net/Stryker-in-pipeline
