### ISSUE TITLE
Migrate website to Docusaurus

### ISSUE THREAD

**Issue by simondel** [stryker-mutator/stryker-mutator.github.io#203]
Docusaurus is a way to generate static websites from markdown. It is different from pug (what we're currently using), in that it uses convention over configuration. See https://github.com/facebook/Docusaurus

It would be great if we could generate the website from the different `docs` directories in the stryker, stryker-net, stryker4s, and mutation-testing-elements repositories. We should move the docs we currently have in the stryker-handbook to one of these 4 (and add a "401 - moved" message on the stryker-handbook once this new website is online).

We should also have some way of authomcatically publishing the latest docs whenever a new version is released (new git tag is created?). That way we can keep the docs up-to-date, but unreleased features won't be visible on the website yet.

TODO:

- [x] Update Docusaurus to latest alpha
- [x] Add FAQ
- [x] Fix docs to Stryker
- [x] Fix docs to handbook. Do after merging?
- [x] Add blog articles and fix blog redirects
- [x] Fix other redirects
- [x] Move stryker handbook docs to website
- [x] Set up mutation-testing-elements docs (and decide on display name)
- [x] Set up new homepage
- [x] Fix contributing guide (min git 2.25 and use git bash on Windows)
- [x] Check all redirect links for the last time

**Comment by simondel** [comment]
Do you want to use Docusaurus v2 straight away? It's currently in alpha: https://v2.docusaurus.io/

**Comment by hugo-vrijswijk** [comment]
I've started on this in #146 in the `docusaurus-docs` branch. It sets up the basic docusaurus repo, and also adds a bash script to pull documentation in the `docs` folder of the two repo's. Currently only Stryker4s and Stryker.NET have their documentation in the docs folder (feel free to create an issue in https://github.com/stryker-mutator/stryker/issues/new).

Most of the actual website content needs to be moved to docusaurus. Including the blogs. For the blogs, a redirect also needs to be set up. That mechanism is already present, but not all the latest blogs have a redirect set up.

**Comment by simondel** [comment]
The webpack support blog has an image with black text, do we want to load a different image when dark mode is active? If so, how?
![image](https://user-images.githubusercontent.com/4221997/97002936-f9502e00-153a-11eb-908a-2a66ad1f1bc7.png)

Light mode:
![image](https://user-images.githubusercontent.com/4221997/97002969-0836e080-153b-11eb-984e-c51adfdc3bd8.png)

**Comment by nicojs** [comment]
I guess this one can be closed 👍

**Comment by nicojs** [comment]
Apparently not, still stuff to do 🤐

**Comment by hugo-vrijswijk** [comment]
Done!
