### ISSUE TITLE
Support canonical urls

### ISSUE THREAD

**Issue by nicojs** [stryker-mutator/stryker-mutator.github.io#204]
We might want to support the reposting of blog articles with canonicalization. 

https://moz.com/learn/seo/canonicalization

**Comment by hugo-vrijswijk** [comment]
For blog posts, you can add a canonical URL in the `head`:

https://github.com/stryker-mutator/stryker-mutator.github.io/blob/085a3648b430023295c13a7b5b2bd2c118640606/blog/2022-08-16-connect-pit-to-stryker-dashboard.md?plain=1#L11-L13
