### ISSUE TITLE
Some feedback from a frontend dev

### ISSUE THREAD

**Issue by Martinspire** [stryker-mutator/stryker-mutator.github.io#233]
So one of my colleagues just implemented Stryker and I was looking at what it was and how it worked and I had a few comments that I wanted to share.

For starters, the whole mutants, mutators and killed part isn't really selling me on this piece of code. I find it confusing and unclear. I needed to look at the documentation what was actually the good bit and what was the bad bit. I would prefer if there was a way to make these more descriptive or even disable the whole Mutants vibe. It also doesn't look professional.

Then when I look at the results, there's not much telling me what it did and why it went good or bad.  When I look at something like this https://stryker-mutator.io/robobar-example/reports/mutation/html/index.html#success-component/success-component.js it doesn't really tell me much. I see the numbers but what do they say and why is the number important? And when clicking them, there's some code inserted but there's very little to go on with what it did and what was expected. I'm guessing you mean that it replaced the test with that and checked whether it failed or succeeded. But the whole survived bit makes it sound like it was good instead of bad. And it doesn't explain why it inserted what it did, it seems quite random and I would imagine it tries more than just 1 change in order to test it is fine but it only shows 1 modification.

The example also doesn't show what the original tests were and what they should be, this makes it easier to understand what it does. I also expected to see more visual examples in the documentation. There's a few code bits, but it never shows you what it will look like when you run it, what the results are and how you should interpret that. And with the whole mutants killing and suriviving, it doesn't make it easier to understand. For a tool that is focussing on improving tests, it doesn't do a good job showing you why, just that its bad. What I mean by this is that on pages like these: https://stryker-mutator.io/docs/mutation-testing-elements/supported-mutators/ I expect to find more about what I need to do to fix this, rather than just "it does x and it breaks" because that doesn't help me write better code and better tests.

I also saw that you need a stryker.conf.json file, adding yet another file to my repository. I wonder if its possible to include the config in other files as well, because I don't really see why this can't be part of something else.

And lastly I expected to find something about integrating with Jenkins or Bitbucket. I do see Travis and Azure/Gitlab, but I don't see these other 2. Whats also strange is that Azure, Gitlab and thus the ones I mentioned aren't supported, which surprised be a lot. It makes stryker unusable for many projects.

I hope this makes clear what my initial experience with this project was and what I think can be improved. Do with it what you will.

**Comment by simondel** [comment]
Thanks for the feedback! I have a few questions:
> For starters, the whole mutants, mutators and killed part isn't really selling me on this piece of code

Which part of the site are you referring to? Perhaps [this](https://stryker-mutator.io/docs/)?

> Then when I look at the results, there's not much telling me what it did and why it went good or bad. When I look at something like this https://stryker-mutator.io/robobar-example/reports/mutation/html/index.html#success-component/success-component.js it doesn't really tell me much. I see the numbers but what do they say and why is the number important? And when clicking them, there's some code inserted but there's very little to go on with what it did and what was expected. 

Where would you expect this documentation?

> The example also doesn't show what the original tests were and what they should be, this makes it easier to understand what it does. I also expected to see more visual examples in the documentation

How would you expect this to be shown? Would a link to the code on GitHub be enough for you?

>  There's a few code bits, but it never shows you what it will look like when you run it, what the results are and how you should interpret that
What is _it_ in this case? The demo application or Stryker?

> I expect to find more about what I need to do to fix this, rather than just "it does x and it breaks" because that doesn't help me write better code and better tests.

Good point! 👍

> I also saw that you need a stryker.conf.json file, adding yet another file to my repository. I wonder if its possible to include the config in other files as well, because I don't really see why this can't be part of something else.

Fair enough. You can use command line arguments, but then the config would be in your package.json

> And lastly I expected to find something about integrating with Jenkins or Bitbucket. I do see Travis and Azure/Gitlab, but I don't see these other 2. Whats also strange is that Azure, Gitlab and thus the ones I mentioned aren't supported, which surprised be a lot. It makes stryker unusable for many projects.

What kind of support would you expect? Executing npm scripts is supported out of the box. Uploading your report to the cloud is currently not supported out of the box for other vendors it requires a specific implementation.

**Comment by Martinspire** [comment]
> Which part of the site are you referring to? Perhaps [this](https://stryker-mutator.io/docs/)?

Yes the docs pages. Though I must add that this page also doesn't tell me much: https://github.com/stryker-mutator/stryker . I think there should be at least a paragraph about "Stryker is about testing your tests by modifying your tests and see if anything breaks" or something.

And to add, if there was a way to show the docs/results while not talking about mutators, killing mutators and stuff but rather about modified tests, fixing bugs instead, that would be neat too. If I show this too my boss and my bosses boss, they have no idea what I'm talking about and wonder why it looks/sounds like a cartoon. I know its fun to use your favorite hobbies together, but I feel this goes a bit too far and makes it a bit troublesome. Especially for folks where English isn't their first language its hard to first translate to the regular words and then to your native tongue. I understand, its not as childish as FartJS, but since its a pretty important topic for projects, perhaps we could do with a bit more professionalism. I would be fine if you keep it this way, I have a funny avatar too, but I hope you will consider my points and do with it what you will.

> > Then when I look at the results, there's not much telling me what it did and why it went good or bad. When I look at something like this https://stryker-mutator.io/robobar-example/reports/mutation/html/index.html#success-component/success-component.js it doesn't really tell me much. I see the numbers but what do they say and why is the number important? And when clicking them, there's some code inserted but there's very little to go on with what it did and what was expected.

> Where would you expect this documentation?

The page that links to it: https://stryker-mutator.io/docs/General/example

Or just a generic page about the results that (perhaps with screenshots) shows what everything means and how it should look like. 

> > The example also doesn't show what the original tests were and what they should be, this makes it easier to understand what it does. I also expected to see more visual examples in the documentation

> How would you expect this to be shown? Would a link to the code on GitHub be enough for you?
Perhaps this is more about the code it runs on so not the GitHub source for this project but rather in the mutator report itself. I'm not sure if it has access to either the tests or the code, but it would help if it links to both of them on the mutator test results. Perhaps something users can configure as where it is located (either relative or direct) because for most people the coverage reports and source code is pretty standard. And if a project is hosted in gitlab/bitbucket/etc, it could (with a prefix) link to the file on there. 

Say I have a discussion about this with my coworkers, it would be very handy if I could go from the mutator results (or link to those) and go to the source and the test file in 1 go. It would save a lot of time going to those files myself and might even save me a meeting that can now be an email ;)

> > There's a few code bits, but it never shows you what it will look like when you run it, what the results are and how you should interpret that

> What is _it_ in this case? The demo application or Stryker?

Both kinda. But in the case of the example I expect to not only see the mistakes, but also the fixes for this situation. A "before" and "after" code snippet would help a lot in understanding why I really need Stryker. Since you use the demo project, having the before test code and after test code, would make it easier to understand what it value it adds and how I should interpret the results.

> > I also saw that you need a stryker.conf.json file, adding yet another file to my repository. I wonder if its possible to include the config in other files as well, because I don't really see why this can't be part of something else.
> Fair enough. You can use command line arguments, but then the config would be in your package.json

I'm fine with either, but I can imagine some admins wanting less separate config files. Since you can also use a subfolder, it doesn't matter much to me right now.

> > And lastly I expected to find something about integrating with Jenkins or Bitbucket. I do see Travis and Azure/Gitlab, but I don't see these other 2. Whats also strange is that Azure, Gitlab and thus the ones I mentioned aren't supported, which surprised be a lot. It makes stryker unusable for many projects.
> What kind of support would you expect? Executing npm scripts is supported out of the box. Uploading your report to the cloud is currently not supported out of the box for other vendors it requires a specific implementation.

I mean that last part, I would like it if it supports more integrations or would link tickets or what have you, to show my support and look for solutions.

Thanks for taking the time to respond, I hope you can take a few points from this in order to make Stryker even better! I hope I wasn't too harsh in my comments. After getting used to it, it does look like a valuable addition.

**Comment by rouke-broersma** [comment]
@Martinspire Late reply but here goes.

I understand your wish for stryker to show you what could be improved. But this is a harder ask than you might realize. What stryker (mutation testing in general) points out is a lack of unit testing and thus a location of _potential_ bugs, but not bugs per se. To point out **how** to fix this, we would have to generate unit tests sufficient for your specific project. This is an immensely difficult thing to do and frankly not currently in the scope of this project. What we can do, and precisely what we do is point out **where** you are lacking unit testing so you can focus your efforts in the right areas of your code base.

Perhaps this clears up some of the frustrations you might have had using stryker.
