### ISSUE TITLE
Running stryker only on changed code

### ISSUE THREAD

**Issue by daniel-candis** [stryker-mutator/stryker-mutator.github.io#234]
Hi there!

Did anyone experiment around with running stryker only on changed code? The usecase for me is not performance, but gradual adoption: At the moment we do not have enough test coverage to enforce killing all mutants, but we would like to enforce this kind of test coverage on new code written.
My current idea is around setting files to the staged non-test files, but maybe there is a better way with this library?

Best,
Daniel

**Comment by hugo-vrijswijk** [comment]
Hi Daniel, thanks for opening this issue. Which Stryker version are you running? Stryker.NET has support for a [diff-mode](https://stryker-mutator.io/docs/stryker-net/Configuration/#diff), but Stryker.js and Stryker4s do not

**Comment by simondel** [comment]
Whoops! I ignored this notification because I thought the reply was on https://github.com/stryker-mutator/stryker/issues/322 which has a similar issue number.

If your question is for Stryker.js, you can find more info in the issue above :)
