### ISSUE TITLE
Implement new menu structure

### ISSUE THREAD

**Issue by nicojs** [stryker-mutator/stryker-mutator.github.io#75]
![image](https://user-images.githubusercontent.com/1828233/44912896-ead7a480-ad2b-11e8-9293-9de752076fce.png)

**Comment by kmdrGroch** [comment]
@nicojs I would like also notice that now it looks bad from 1050px to 770px width
![image](https://user-images.githubusercontent.com/28489774/44914647-24f77500-ad31-11e8-9468-a8c4428c271e.png)

**Comment by nicojs** [comment]
Done in the redesign branch

@kmdrGroch Could you take a look using the redesign branch? It should scale beautifully there
