### ISSUE TITLE
HTTPS instead of HTTP

### ISSUE THREAD

**Issue by kmdrGroch** [stryker-mutator/stryker-mutator.github.io#76]
You should really think about changing protocol to safe one.
maybe it should work? https://help.github.com/articles/securing-your-github-pages-site-with-https/

**Comment by nicojs** [comment]
Hmm It would be cool to enforce https. It doesn't seem possible at the moment. @ptoonen this is because of our setup with cloudflare? Should be possible, no?

![image](https://user-images.githubusercontent.com/1828233/45922448-952a8e00-becc-11e8-9482-0eea5dd9d2ed.png)

**Comment by ptoonen** [comment]
It should be possible, let's take a look somewhere this week :-)

**Comment by ptoonen** [comment]
This has been implemented on all services (badge, dashboard and website) for a while now. I'm closing this issue :) Thanks for the suggestion @kmdrGroch.
