### ISSUE TITLE
Improve "Meet Stryker" text

### ISSUE THREAD

**Issue by nicojs** [stryker-mutator/stryker-mutator.github.io#84]
On our 'redesign' branch, we now have this text:

> ## Meet Stryker
> 
> With Stryker, we bring mutation testing to the masses.
>                 It takes the best practices of existing mutation testing frameworks like [PIT](http://pitest.org/) and [Infection](https://infection.github.io/),
>                 but with the open mentality of nodejs and the web. This is why Stryker is not a test runner or test framework.
>                 Indeed, why would it? There are already awesome test runners and test frameworks out there.
>                 Instead, Stryker empowers you to use what you like and focusses on being the best Mutation testing framework it can be.

This is sort of a mix from the old text with "JavaScript" removed. We should find something better.

@simondel @hugo-vrijswijk @richardwerkman @kmdrGroch @philippw @ArpadK any ideas?

**Comment by kmdrGroch** [comment]
```
Meet Stryker
Stryker is an awesome mutation testing system. It takes the best practices of existing mutation testing frameworks like PIT and Infection, but with the open mentality of different environments. This is why Stryker is not a test runner or test framework.
Why Stryker?
Because Stryker empowers you to use what you like and focusses on being the best Mutation testing framework it can be.
Download it now and create own mutants today.

**Comment by kmdrGroch** [comment]
We should concentrate more on `awesomeness` of stryker than testing frameworks. Also ``we bring mutation testing to the masses`` doesn't sound cool to me.
We could also add some information about mutation tests themselves like PIT has.

**Comment by nicojs** [comment]
Thanks @kmdrGroch, I agree with you. How about this:

> ## Meet: Stryker

> Don't worry, Stryker has your back. It uses one design mentality to implement 
> mutation testing on 3 platforms.
> It's _easy to use_ and _fast to run_, but without those nasty false  positives.

Sounds better right?

> We could also add some information about mutation tests themselves like PIT has.

We already have the "What is mutation testing?" and "But wait, what about code coverage?". You want even more of an introduction? I've also added the example page. It should allow people to try it themselves, or at least being able to compare code coverage and mutation testing.

**Comment by kmdrGroch** [comment]
Yea we can make some example page with for example ``add`` function as the simplest example.
if you have function
```javascript
function add(a, b) {
   if(typeof a !== "number" || typeof b !== "number") throw TypeError("parameters should be numbers");
   return a + b;
}
```
Then tests:
expect(add(13, "21")).toThrow(new TypeError("parameters should be numbers"));

And after running stryker you will get:
``return a + b;`` -> ``return a - b`` mutation passed


also what do you mean by "It's easy to use and fast to run, but without those nasty false positives."

and. We do have "what is mutation testing"? I havent noticed that.

**Comment by kmdrGroch** [comment]
and if we end up making this "Improve stryker" text until next week, I will be able to have this checked by native speaker. :)

**Comment by nicojs** [comment]
> Yea we can make some example page with for example add function as the simplest example.

Feel free to take a look at the example page in the redesign branch. If we need to explain an example, I would like to take the age check from the robobar as the example to explain. It is simple to understand (underage people cannot drink alcohol) and the people can actually see the problems themselves in the example reports.

**Comment by nicojs** [comment]
> also what do you mean by "It's easy to use and fast to run, but without those nasty false positives."

Well, Stryker (all 3 versions) always mutates _source code_ rather than bytecode, ik code, minified JavaScript, etc. This is the difference with what PIT does right now. I'll clearify it further. Good point

**Comment by kmdrGroch** [comment]
Nice. I will look at it in free time :)

**Comment by nicojs** [comment]
That sounds great! Would love to get me some of that _free time_ myself some day 😓. Seriously though, we're probably publishing this today/tonight. Improvements can still be made after. Thanks for reviewing!

**Comment by kmdrGroch** [comment]
Ive got my schedule at the university. i'll have free time only thursday - sunday (other days up to 6pm)

**Comment by hugo-vrijswijk** [comment]
I'm not convinced by starting the text with "Don't worry". It makes you feel like there _is_ something to worry about. I'd also say the design mentality isn't that interesting for the header text, more something for later detail

**Comment by nicojs** [comment]
How about: "Still confused? Don't worry...."
