### ISSUE TITLE
Minify css

### ISSUE THREAD

**Issue by nicojs** [stryker-mutator/stryker-mutator.github.io#88]
Css compilation in webpack doens't seem to be minified. (still on redesign branch for now)

**Comment by kmdrGroch** [comment]
Done. Solution in (https://github.com/stryker-mutator/stryker-mutator.github.io/commit/493ec66811b6d4120e12b93373d54b636aa90d3c#comments)

**Comment by kmdrGroch** [comment]
@nicojs issue to close :)
