### ISSUE TITLE
index.pug text changes

### ISSUE THREAD

**Issue by kmdrGroch** [stryker-mutator/stryker-mutator.github.io#92]
In lines 8-9:
```
 With a rich set of mutators specifically for Scala you will be able to test bugs in ways you never knew possible!
 Currently Stryker4s is still in heavy early development, this means it's propably not ready for large projects just yet.
```
i would make some changes:

``test bugs in ways you never knew possible!`` -> I don't even get what author mean by `never knew possible!` (it doesn't sound like english). Maybe ``test bugs in ways you possibly have never known``?

``Currently Stryker4s is still in heavy early development, this means it's propably not ready for large projects just yet.`` -> ``Currently Stryker4s is still in heavy early development, which means it's propably not ready for large projects just yet.`` or ``Currently Stryker4s is still in heavy early development. This means it's propably not ready for large projects just yet.``

**Comment by nicojs** [comment]
@hugo-vrijswijk @legopiraat this is the index.pug for the scala part. You mind taking a look?

@kmdrGroch thanks again for a thorough review

**Comment by legopiraat** [comment]
@kmdrGroch would you mind taking a look at https://github.com/stryker-mutator/stryker-mutator.github.io/pull/95 ? Hopefully this is a bit better.
