### ISSUE TITLE
Navbar - "for javascript"

### ISSUE THREAD

**Issue by kmdrGroch** [stryker-mutator/stryker-mutator.github.io#96]
I've noticed there is ``for Javascript`` in Navbar. But it is also for typescript, angular, react (which is javascript at all but you know).

Maybe instead of ``for javascript`` we should write ``for Web`` or sth like this.
What is your opinion?

**Comment by hugo-vrijswijk** [comment]
`for Web` isn't completely accurate either, with Node being able to run server-side and even in applications. There's already `JavaScript & friends`, but maybe `for Node` paints a more accurate picture?

**Comment by kmdrGroch** [comment]
well.. people dont have to know about Node (even if stryker is being downloaded using node). It is hard topic... "javascript" can stay if there is no better idea :/

**Comment by nicojs** [comment]
It should be "for JavaScript & friends". That's the most accurate and consistent way of describing the damn thing. Problem was it took too much space. I'll try again tomorrow. 

How about "For JS & Friends"?

**Comment by kmdrGroch** [comment]
LGTM :)

**Comment by simondel** [comment]
We could try `For JS & Friends` but it might be a bit vague because you could also consider Stryker.NET and Stryker4S friends.
