### ISSUE TITLE
Spelling, grammar etc.

### ISSUE THREAD

**Issue by kmdrGroch** [stryker-mutator/stryker-mutator.github.io#97]
If it is possible, I would like all PR connected to "text" to be resolved, then we should all check through all files, if there is proper grammar and no misspells. If we do it until the end of this week, I should be able to show it to native speaker too.

**Comment by kmdrGroch** [comment]
Known issues:
homepage:
```
Bugs, or mutants, are automatically inserted into your production code. Your `tests are run` for each mutant.
```

**Comment by nicojs** [comment]
I'm not sure what the kind of grammar issues you're referring to here. Can you make a PR per spell check issue or file?

**Comment by kmdrGroch** [comment]
I'm reffering to spelling issues, and also like construction issues. I'll be able to produce PR in Thursday to cover some of them
