### ISSUE TITLE
Make the "develop" branch an orphan branch

### ISSUE THREAD

**Issue by nicojs** [stryker-mutator/stryker-mutator.github.io#99]
Github tries to help us by suggesting to merge back to master every time.

![image](https://user-images.githubusercontent.com/1828233/46313981-95f8a980-c5c9-11e8-9516-80493ec98dea.png)

We should never ever ever ever allow that to happen. Sources should be merged to develop. In order to make sure this can never go wrong, I want to recreate "develop" as an orphan branch. Orphan branches basically allows multiple git repos to exist in a single git repo. Develop can then never be merged to master, as they don't share history.

Doing this can be confusing for people that already have a local develop branch tracking the remote. That's why we should do this at a good moment in time, preferably when there are no open PRs

**Comment by hugo-vrijswijk** [comment]
Doesn't GitHub also allow 'default' branches? Or will that affect the GitHub pages?

**Comment by nicojs** [comment]
Even so, I would like to block people from incidentally pushing to master. This is what an orphan branch is designed to do.

BTW, I'm I talking to a cat or to a person? 🐱

**Comment by simondel** [comment]
Cat. Definitely cat. 😻

**Comment by nicojs** [comment]
I've forced pushed master as a orphan branch. Anyone still on the "old master", please use these commands (although you shouldn't ever need the master branch locally)

```shell
git branch -D master
git fetch origin
git branch master --track origin/master
```

**Comment by nicojs** [comment]
I've also made `develop` the default branch btw, so no more incidental PR's.
